### ISSUE TITLE
Errors Building Samples Browser

### ISSUE THREAD

**Issue by trinare** [Infragistics/wpf-samples#26]
I'm trying to build the Samples Browser. I have Visual Studio 2022. The .NET 4.0 Targeting Pack is no longer available with Visual Studio, so I tried upgrading the projects to .NET 4.8, but I'm getting errors building the solution:

```
The tag 'SampleContainer' does not exist in XML namespace 'clr-namespace:Infragistics.Samples.Framework;assembly=Infragistics.Samples.Shared'. Line 1 Position 30.			
```

In Project IGToolbar.xaml

In the following files:

CustomAction.xaml
DataChartIntegration.xaml
LayoutActions.xaml
VerticalOrientation.xaml
Theming.xaml

**Comment by IGvaleries** [comment]
Hello trinare,
the samples browser has been updated to use .Net4.7 now so this should resolve any issue you were having using it with VS 2022. Please get the latest on the master branch and let me know if you have any issues.
Thanks,
Valerie

**Comment by trinare** [comment]
It's working now! Thanks!
