### ISSUE TITLE
DataLegend Grouping samples does not group legend items

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [Infragistics/wpf-samples#28]
legend items should be grouped into at least 2 different groups
legend's group header should be visible

<img width="660" alt="image" src="https://github.com/user-attachments/assets/d887cdd1-24c5-4ade-ad08-f62117c39f79">

**Comment by mddifilippo89** [comment]
https://github.com/Infragistics/wpf-samples/pull/37
